name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # At 00:00 on Monday.
    - cron: "0 0 * * 1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          # - "1.7"
          # - "1.8"
          # - "1.9"
          # - "1.10"
          # - "1.11"
          # - "1.12"
          # - "1.13"
          # - "1.14"
          - "1.15"
          - "1.16"
          - "1.17"
          - "1.18"
    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Publish to GitHub Container Registry
        env:
          REGISTRY: ghcr.io/appscode
          DOCKER_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
          USERNAME: 1gtm
        run: |
          docker login ghcr.io --username ${USERNAME} --password ${DOCKER_TOKEN}
          make release RELEASE=${{ matrix.k8s }}

      - name: Publish to Docker Registry
        env:
          REGISTRY: appscode
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          USERNAME: 1gtm
        run: |
          docker login --username ${USERNAME} --password ${DOCKER_TOKEN}
          make release RELEASE=${{ matrix.k8s }}
